.gitignore, README.md, cmd/uv3dp/bed.go, cmd/uv3dp/main.go, format.go
=> Issue 1 help to stderr

README.md, cmd/uv3dp/exposure.go, cmd/uv3dp/info.go, printable.go, properties.go, sl1/format.go, sl1/format_test.go
=> sl1: Support both 'numSlow' and 'numFade' bottom styles

README.md, cmd/uv3dp/command.go, cmd/uv3dp/command_test.go, cmd/uv3dp/main.go
=> cmd/uv3dp: Add '@command.cmd' file parsing

README.md, cmd/uv3dp/bed.go, cmd/uv3dp/empty.go, cmd/uv3dp/init.go, cmd/uv3dp/machine.go, cover.sh, format.go
=> Issue 14 empty bed command

README.md, cbddlp/format.go, cbddlp/format_alias_test.go, cbddlp/format_empty_test.go, check.sh, cmd/uv3dp/bed.go, cmd/uv3dp/empty.go, cmd/uv3dp/exposure.go, cmd/uv3dp/info.go, cmd/uv3dp/machine.go, cmd/uv3dp/main.go, cmd/uv3dp/resin.go, properties.go, sl1/format.go, sl1/format_test.go
=> cmd/uv3dp: Look up resin from ChiTuBox config

cbddlp/rle.go
- Fixes #20
Signed-off-by: Jason S. McMullan <jason.mcmullan@gmail.com>
=> cbddlp/rle: Fix issues with RLE15 encoding

README.md, cbddlp/rle.go
=> cbddlp: Excess debug messages

README.md, cbddlp/format.go, cmd/uv3dp/bottom.go, cmd/uv3dp/exposure.go, cmd/uv3dp/info.go, cmd/uv3dp/lift.go, cmd/uv3dp/main.go, cmd/uv3dp/resin.go, cmd/uv3dp/resin_map.go, cmd/uv3dp/retract.go
- Fixes #25 
Signed-off-by: Jason S. McMullan <jason.mcmullan@gmail.com>
=> cmd/uv3dp: Split 'exposure' into multiple commands

README.md, cmd/uv3dp/decimate.go, decimate.go
=> decimate: Add # of Passes and bottom/normal only modes

cbddlp/format.go, ctb/format.go, phz/format.go, printable.go
Summary:
- Fixes #45 
- Integrate patch provided by @ddv2005 as a general solution
=> memory usage: Reduce memory usage when converting to ctb/cbddlp/phz

.github/workflows/release.yml, README.md, cmd/uv3dp/main.go
=> cmd: Add '--version' flags

README.md, cmd/uv3dp/main.go, printable.go, progress.go
=> uv3dp: Add progress indicator (optional)

.gitignore, cws/format.go, printable.go, sl1/format.go, uvj/format.go
=> uvj/cws/sl1: Fix missing --progress information

cmd/uv3dp/machine.go
=> pw0: Fix Photon Zero machine size typo

cmd/uv3dp/machine.go
Add CBD-TECH based Kelant S400 as per #68
=> Kelant S400 CBDDLP

README.md, cbddlp/format.go, cbddlp/format_alias_test.go, cbddlp/format_empty_test.go, cmd/uv3dp/bottom.go, cmd/uv3dp/exposure.go, cmd/uv3dp/info.go, ctb/format.go, ctb/format_empty_test.go, cws/format.go, phz/format.go, phz/format_empty_test.go, properties.go, pws/format.go, pws/format_test.go, sl1/format.go, uvj/format_test.go, zcodex/format.go
=> cbddlp/ctb/phz: Add support for reading/saving PWM values

README.md, check.sh, uvj/README.md
=> uvj documentation

pws/format.go, pws/rle1.go
=> pws: Encode using the same count-of-threshold method as CBDDLP

README.md, cbddlp/format.go
=> cbddlp: Clamp to a max of 16 for AA

README.md, cmd/uv3dp/decimate.go
=> cmd: Allow decimate to operate on both bottom and normal layers at once

README.md, cmd/uv3dp/machine.go
Merge in https://github.com/expipiplus1/uv3dp/tree/correct-spelling
=> Elogoo -> Elegoo

cws/format.go, cws/format_test.go
=> cws: Correct some issues with formatting

README.md, cmd/uv3dp/main.go, lgs/format.go, lgs/init.go, lgs/rle.go, properties.go
=> lgs: Add Longer Orange 10 & 30 support

README.md, ctb/format.go, properties.go, sl1/format.go, sl1/format_test.go, uvj/format_test.go
=> uvj: Add support for transition layers

README.md, cmd/uv3dp/empty.go, cmd/uv3dp/resin_map.go, ctb/init.go
=> Issue 132 e6 e10 support

ctb/format.go
=> ctb: Enable per-layer timing flag for CTB v3

cmd/uv3dp/check.go
=> cmd/uv3dp: Add safety check before saving
